version: '3.9'

services:
  dev:
    container_name: dev-app-userway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: "npm run start:dev"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - dev-network-userway
    restart: always

  postgres:
    image: postgres:alpine
    container_name: dev-postgres-userway
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./src/db/pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - dev-network-userway
    restart: always

  redis:
    image: "redis:alpine"
    container_name: dev-redis-userway
    ports:
      - "6379:6379"
    volumes:
      - ./src/redis/data:/data
    networks:
      - dev-network-userway
    restart: always

networks:
  dev-network-userway:
    driver: bridge

volumes:
  postgres-data-dev:
