version: '3.9'

services:
  dev-app:
    container_name: dev-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: "npm run start:dev"
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - dev-network
    restart: always

  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - dev-network
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - dev-network
    restart: always
